# Generated by Django 5.2.3 on 2025-06-23 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('count_per_pack', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('stock_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('cash_balance', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'weekday',
                    models.CharField(
                        choices=[
                            ('Mon', 'Monday'),
                            ('Tue', 'Tuesday'),
                            ('Wed', 'Wednesday'),
                            ('Thur', 'Thursday'),
                            ('Fri', 'Friday'),
                            ('Sat', 'Saturday'),
                            ('Sun', 'Sunday'),
                        ],
                        max_length=4,
                    ),
                ),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                (
                    'pharmacy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='pharmacy.pharmacy',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy_name', models.CharField(max_length=50)),
                ('inventory_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('count_per_pack', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                (
                    'inventory',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='pharmacy.inventory',
                    ),
                ),
                (
                    'pharmacy',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='pharmacy.pharmacy',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='pharmacy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('pharmacy', 'name', 'color', 'count_per_pack')},
        ),
    ]
