name: ci-workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  python-linter-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Sync uv environment
        run: |
          cd backend
          uv sync
          cd ..

      - name: Run pre-commit hooks with uv
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files"

      - name: Run Unit tests
        run: |
          cd backend/src
          uv run pytest -vv --cov=core --cov-report=xml
          cd ..
        env:
          SECRET_KEY: unsafe-secret-key-for-ci-workflow
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
